services:
 - type: web
    name: my-web-service
    buildCommand: python -m venv venv && source venv/bin/activate && pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:8080 --workers 1 --threads 8 --timeout 600 wsgi:application
    env: {}
